# Generated by Django 6.0 on 2025-12-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('TOP_UP', 'Top Up'), ('SUBSCRIPTION', 'Subscription Payment'), ('ADJUSTMENT', 'Manual Adjustment'), ('PUBLISH_FEE', 'Publication Fee')], max_length=20),
        ),
    ]
