# Generated by Django 6.0 on 2025-12-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
