# Generated by Django 6.0 on 2025-12-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_article_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
