# Generated by Django 6.0 on 2026-01-08 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_articlereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articlereview',
            unique_together={('article', 'expert')},
        ),
    ]
