# Generated by Django 6.0 on 2026-01-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_finance_admin',
            field=models.BooleanField(default=False, help_text='Finance admin access'),
        ),
    ]
