# Generated by Django 6.0 on 2026-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_finance_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False, help_text='Expert user who can write article critiques'),
        ),
    ]
